### PR TITLE
Provide support for pwa with nuxt-js template and other fixes

### LINKED ISSUE #74: Add provision to have pwa support for Nuxt-js template
Currently, the user can only have the basic template if he chooses `Nuxt-js` from the list.
It should be made such that the user will be prompted whether he/she requires `pwa` support after making the selection as mentioned above. 
See these [guidelines](https://pwa.nuxtjs.org/setup.html)

### PR DESCRIPTION
**Pull request by aquibbaig**
Closes #74 
- Made an entry to `mevn.json` if the user wishes to have `pwa` support as part of `Nuxt-js` boilerplate template and proceeds further with the installation.
- Sets up `pwa` configuration with the `Nuxt-js` template as required.
- Use `open` package instead of `opn` which is deprecated.
- Other minor bug fixes

### CODE REVIEW

File: src/commands/basic/init.js [hunk 1]
```diff
@@ -99,6 +99,24 @@ const fetchTemplate = async template => {
     );
 
     if (template === 'nuxt') {
+      await inquirer.prompt([{
+        name: 'pwa',
+        type: 'confirm',
+        message: 'Pwa support?'
```
Comment (jamesgeorge007) [inline src/commands/basic/init.js]:
```suggestion
        message: 'Do you require pwa support'
```
